package Classes;
import java.util.List;

public class Currencies {

    //Lista de moedas
    private static final List<Currency> CURRENCIES = List.of(
            new Currency("CAD", "Dólar Canadense", "Canadá"),
            new Currency("AED", "Dirham dos Emir. Árabes Unidos", "Emirados Árabes Unidos"),
            new Currency("AFN", "Afegane", "Afeganistão"),
            new Currency("ALL", "Lek", "Albânia"),
            new Currency("AMD", "Dram Armênio", "Armênia"),
            new Currency("ANG", "Florim das Antilhas Holandesas", "Antilhas Holandesas"),
            new Currency("AOA", "Kwanza", "Angola"),
            new Currency("ARS", "Peso Argentino", "Argentina"),
            new Currency("AUD", "Dólar Australiano", "Austrália"),
            new Currency("AWG", "Florim Arubano", "Aruba"),
            new Currency("AZN", "Manat Azerbaijano", "Azerbaijão"),
            new Currency("BAM", "Marco Convertible", "Bósnia e Herzegovina"),
            new Currency("BBD", "Dólar de Barbados", "Barbados"),
            new Currency("BDT", "Taka", "Bangladesh"),
            new Currency("BGN", "Lev Búlgaro", "Bulgária"),
            new Currency("BHD", "Dinar Bareinita", "Bahrein"),
            new Currency("BIF", "Franco Burundês", "Burundi"),
            new Currency("BMD", "Dólar das Bermudas", "Bermudas"),
            new Currency("BND", "Dólar do Brunei", "Brunei"),
            new Currency("BOB", "Boliviano", "Bolívia"),
            new Currency("BRL", "Real Brasileiro", "Brasil"),
            new Currency("BSD", "Dólar das Bahamas", "Bahamas"),
            new Currency("BTN", "Ngultrum", "Butão"),
            new Currency("BWP", "Pula", "Botswana"),
            new Currency("BYN", "Rublo Bielorrusso", "Bielorrússia"),
            new Currency("BZD", "Dólar de Belize", "Belize"),
            new Currency("CDF", "Franco Congolês", "Congo"),
            new Currency("CHF", "Franco Suíço", "Suíça"),
            new Currency("CLP", "Peso Chileno", "Chile"),
            new Currency("CNY", "Yuan Chinês", "China"),
            new Currency("COP", "Peso Colombiano", "Colômbia"),
            new Currency("CRC", "Colón Costarriquenho", "Costa Rica"),
            new Currency("CUP", "Peso Cubano", "Cuba"),
            new Currency("CVE", "Escudo Cabo-Verdiano", "Cabo Verde"),
            new Currency("CZK", "Coroa Checa", "República Tcheca"),
            new Currency("DJF", "Franco Djiboutiano", "Djibouti"),
            new Currency("DKK", "Coroa Dinamarquesa", "Dinamarca"),
            new Currency("DOP", "Peso Dominicano", "República Dominicana"),
            new Currency("DZD", "Dinar Argelino", "Argélia"),
            new Currency("EGP", "Libra Egípcia", "Egito"),
            new Currency("ERN", "Nakfa", "Eritreia"),
            new Currency("ETB", "Birr Etíope", "Etiópia"),
            new Currency("EUR", "Euro", "União Europeia"),
            new Currency("FJD", "Dólar de Fiji", "Fiji"),
            new Currency("FKP", "Libra das Ilhas Malvinas", "Ilhas Malvinas"),
            new Currency("FOK", "Coroa das Ilhas Faroe", "Ilhas Faroe"),
            new Currency("GBP", "Libra Esterlina", "Reino Unido"),
            new Currency("GEL", "Lari Georgiano", "Geórgia"),
            new Currency("GGP", "Libra de Guernsey", "Guernsey"),
            new Currency("GHS", "Cedi Ganês", "Gana"),
            new Currency("GIP", "Libra de Gibraltar", "Gibraltar"),
            new Currency("GMD", "Dalasi", "Gâmbia"),
            new Currency("GNF", "Franco Guineense", "Guiné"),
            new Currency("GTQ", "Quetzal Guatemalteco", "Guatemala"),
            new Currency("GYD", "Dólar da Guiana", "Guiana"),
            new Currency("HKD", "Dólar de Hong Kong", "Hong Kong"),
            new Currency("HNL", "Lempira", "Honduras"),
            new Currency("HRK", "Kuna Croata", "Croácia"),
            new Currency("HTG", "Gourde Haitiano", "Haiti"),
            new Currency("HUF", "Forint Húngaro", "Hungria"),
            new Currency("IDR", "Rupia Indonésia", "Indonésia"),
            new Currency("ILS", "Novo Shekel Israelense", "Israel"),
            new Currency("IMP", "Libra da Ilha de Man", "Ilha de Man"),
            new Currency("INR", "Rupia Indiana", "Índia"),
            new Currency("IQD", "Dinar Iraquiano", "Iraque"),
            new Currency("IRR", "Rial Iraniano", "Irã"),
            new Currency("ISK", "Coroa Islandesa", "Islândia"),
            new Currency("JEP", "Libra de Jersey", "Jersey"),
            new Currency("JMD", "Dólar Jamaicano", "Jamaica"),
            new Currency("JOD", "Dinar Jordaniano", "Jordânia"),
            new Currency("JPY", "Iene Japonês", "Japão"),
            new Currency("KES", "Xelim Queniano", "Quênia"),
            new Currency("KGS", "Som Quirguiz", "Quirguistão"),
            new Currency("KHR", "Riel Cambojano", "Camboja"),
            new Currency("KID", "Dólar de Kiribati", "Kiribati"),
            new Currency("KMF", "Franco Comorense", "Comores"),
            new Currency("KRW", "Won Sul-Coreano", "Coreia do Sul"),
            new Currency("KWD", "Dinar Kuwaitiano", "Kuwait"),
            new Currency("KYD", "Dólar das Ilhas Cayman", "Ilhas Cayman"),
            new Currency("KZT", "Tenge Cazaque", "Cazaquistão"),
            new Currency("LAK", "Kip", "Laos"),
            new Currency("LBP", "Libra Libanesa", "Líbano"),
            new Currency("LKR", "Rupia Cingalesa", "Sri Lanka"),
            new Currency("LRD", "Dólar Liberiano", "Libéria"),
            new Currency("LSL", "Loti", "Lesoto"),
            new Currency("LYD", "Dinar Líbio", "Líbia"),
            new Currency("MAD", "Dirham Marroquino", "Marrocos"),
            new Currency("MDL", "Leu Moldavo", "Moldávia"),
            new Currency("MGA", "Ariary Malgaxe", "Madagascar"),
            new Currency("MKD", "Dinar Macedônio", "Macedônia"),
            new Currency("MMK", "Kyat", "Mianmar"),
            new Currency("MNT", "Tugrik", "Mongólia"),
            new Currency("MOP", "Pataca", "Macau"),
            new Currency("MRU", "Ouguiya Mauritana", "Mauritânia"),
            new Currency("MUR", "Rupia Mauriciana", "Maurício"),
            new Currency("MVR", "Rufiyaa", "Maldivas"),
            new Currency("MWK", "Kwacha Malauiano", "Malawi"),
            new Currency("MXN", "Peso Mexicano", "México"),
            new Currency("MYR", "Ringgit Malaio", "Malásia"),
            new Currency("MZN", "Metical", "Moçambique"),
            new Currency("NAD", "Dólar Namibiano", "Namíbia"),
            new Currency("NGN", "Naira Nigeriana", "Nigéria"),
            new Currency("NIO", "Córdoba", "Nicarágua"),
            new Currency("NOK", "Coroa Norueguesa", "Noruega"),
            new Currency("NPR", "Rupia Nepalesa", "Nepal"),
            new Currency("NZD", "Dólar Neozelandês", "Nova Zelândia"),
            new Currency("OMR", "Rial Omanense", "Omã"),
            new Currency("PAB", "Balboa", "Panamá"),
            new Currency("PEN", "Sol Peruano", "Peru"),
            new Currency("PGK", "Kina", "Papua Nova Guiné"),
            new Currency("PHP", "Peso Filipino", "Filipinas"),
            new Currency("PKR", "Rupia Paquistanesa", "Paquistão"),
            new Currency("PLN", "Zloty Polonês", "Polônia"),
            new Currency("PYG", "Guarani", "Paraguai"),
            new Currency("QAR", "Rial Catarense", "Catar"),
            new Currency("RON", "Leu Romeno", "Romênia"),
            new Currency("RSD", "Dinar Sérvio", "Sérvia"),
            new Currency("RUB", "Rublo Russo", "Rússia"),
            new Currency("RWF", "Franco Ruandês", "Ruanda"),
            new Currency("SAR", "Rial Saudita", "Arábia Saudita"),
            new Currency("SBD", "Dólar das Ilhas Salomão", "Ilhas Salomão"),
            new Currency("SCR", "Rupia de Seicheles", "Seicheles"),
            new Currency("SDG", "Libra Sudanesa", "Sudão"),
            new Currency("SEK", "Coroa Sueca", "Suécia"),
            new Currency("SGD", "Dólar de Singapura", "Singapura"),
            new Currency("SHP", "Libra de Santa Helena", "Santa Helena"),
            new Currency("SLE", "Leone", "Serra Leoa"),
            new Currency("SLL", "Leone", "Serra Leoa"),
            new Currency("SOS", "Xelim Somali", "Somália"),
            new Currency("SRD", "Dólar do Suriname", "Suriname"),
            new Currency("SSP", "Libra Sul-Sudanesa", "Sudão do Sul"),
            new Currency("STN", "Dobra", "São Tomé e Príncipe"),
            new Currency("SYP", "Libra Síria", "Síria"),
            new Currency("SZL", "Lilangeni", "Essuatíni"),
            new Currency("THB", "Baht Tailandês", "Tailândia"),
            new Currency("TJS", "Somoni", "Tajiquistão"),
            new Currency("TMT", "Manat Turcomeno", "Turcomenistão"),
            new Currency("TND", "Dinar Tunisiano", "Tunísia"),
            new Currency("TOP", "Pa'anga", "Tonga"),
            new Currency("TRY", "Lira Turca", "Turquia"),
            new Currency("TTD", "Dólar de Trinidad e Tobago", "Trinidad e Tobago"),
            new Currency("TVD", "Dólar Tuvaluano", "Tuvalu"),
            new Currency("TWD", "Novo Dólar Taiwanês", "Taiwan"),
            new Currency("TZS", "Xelim Tanzaniano", "Tanzânia"),
            new Currency("UAH", "Hryvnia Ucraniana", "Ucrânia"),
            new Currency("UGX", "Xelim Ugandense", "Uganda"),
            new Currency("USD", "Dólar Americano", "Estados Unidos"),
            new Currency("UYU", "Peso Uruguaio", "Uruguai"),
            new Currency("UZS", "Som Uzbeque", "Uzbequistão"),
            new Currency("VES", "Bolívar Venezuelano", "Venezuela"),
            new Currency("VND", "Dong Vietnamita", "Vietnã"),
            new Currency("VUV", "Vatu", "Vanuatu"),
            new Currency("WST", "Tala", "Samoa"),
            new Currency("XAF", "Franco CFA BEAC", "Camarões"),
            new Currency("XCD", "Dólar do Caribe Oriental", "Antígua e Barbuda"),
            new Currency("XDR", "Direito Especial de Saque", "Fundo Monetário Internacional"),
            new Currency("XOF", "Franco CFA BCEAO", "Benim"),
            new Currency("XPF", "Franco CFP", "Polinésia Francesa"),
            new Currency("YER", "Rial Iemenita", "Iêmen"),
            new Currency("ZAR", "Rand", "África do Sul"),
            new Currency("ZMW", "Kwacha Zambiano", "Zâmbia"),
            new Currency("ZWL", "Dólar Zimbabuano", "Zimbábue")
    );

    // Método para exibir todas as moedas da lista de moedas
    public static void displayCurrencies() {
        // Cabeçalho da tabela com colunas "Sigla", "Moeda" e "País"
        System.out.printf("%-10s %-30s %-55s\n", "Sigla", "Moeda", "País");
        // Linha de separação abaixo do cabeçalho
        System.out.println("==============================================");
        // Loop através de cada objeto
        for (Currency currency : CURRENCIES) {
            // Exibe os atributos symbol, name e country de cada objeto
            System.out.printf("%-10s %-30s %-50s\n", currency.symbol(), currency.name(), currency.country());
        }
    }
    // Declaração do record Currency com os atributos symbol, name e country
    public record Currency(String symbol, String name, String country) {}
}